Attempt to fix error TS2345
 Argument of type '{ type: string; }' is not assignable to parameter of type 'Action'.

Property 'payload' is missing in type '{ type: string; }' but required in type 'withoutPayload'.